# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('osversion', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('vendor_id', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('cpu_core', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('sn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IpManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=50)),
                ('ip', models.GenericIPAddressField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IpGroup')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Hardware_info')),
            ],
        ),
        migrations.CreateModel(
            name='IpUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.CharField(choices=[('ssh-password', 'SSH/Password'), ('ssh-key', 'SSH/KEY')], help_text='\u5982\u679c\u9009\u62e9SSH/KEY\uff0c\u8bf7\u786e\u4fdd\u4f60\u7684\u79c1\u94a5\u6587\u4ef6\u5df2\u5728settings.py\u4e2d\u6307\u5b9a', max_length=16)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(blank=True, help_text='\u5982\u679cauth_method\u9009\u62e9\u7684\u662fSSH/KEY,\u90a3\u6b64\u5904\u4e0d\u9700\u8981\u586b\u5199..', max_length=64, null=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('cron_type', models.CharField(choices=[(0, '\u547d\u4ee4\u6267\u884c'), (1, '\u811a\u672c\u6267\u884c')], max_length=10)),
                ('cron_content', models.CharField(max_length=50)),
                ('cron_start_time', models.DateTimeField(auto_now=True, null=True)),
                ('cron_total_time', models.CharField(blank=True, max_length=10, null=True)),
                ('cron_result', models.CharField(choices=[(0, '\u7b49\u5f85\u6267\u884c'), (1, '\u6b63\u5728\u6267\u884c'), (2, '\u5df2\u7ecf\u6267\u884c'), (3, '\u6267\u884c\u5931\u8d25'), (4, '\u6267\u884c\u6210\u529f')], default='0', max_length=10)),
                ('cron_status', models.CharField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528')], default='0', max_length=10)),
                ('remark', models.CharField(max_length=100)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IpGroup')),
            ],
        ),
        migrations.AddField(
            model_name='ipmanage',
            name='host_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.IpUsers'),
        ),
    ]
