# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmanage',
            name='port',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
