# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20160324_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanage',
            name='cmds',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
