# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_taskmanage_cmds'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanage',
            name='cron_end_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
