# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_taskdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
