# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20160330_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanage',
            name='cron_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
