# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpu_io_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_loads', models.CharField(max_length=64)),
                ('io_values', models.CharField(max_length=64)),
                ('info_times', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_values', models.CharField(max_length=64)),
                ('mem_times', models.CharField(max_length=64)),
            ],
        ),
    ]
