# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu_io_info',
            old_name='cpu_loads',
            new_name='cpu_loads_val',
        ),
        migrations.RenameField(
            model_name='cpu_io_info',
            old_name='io_values',
            new_name='cpu_type',
        ),
    ]
