# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20160412_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cpu_io_info',
            new_name='cpu_load_info',
        ),
    ]
